import type { Locale } from "@qardan/shared";

/**
 * Textes de l'APPLICATION MOBILE.
 * Le français est la source de vérité typée : `mobileAr` est typé `MobileUi`, donc une
 * clé ajoutée ici et oubliée en arabe casse le typecheck.
 *
 * Les libellés métier (programmes, opérateurs, erreurs, rôles) viennent de
 * `@qardan/shared` — ne rien redéfinir ici.
 */

export const mobileFr = {
  tabs: {
    home: "Accueil",
    programs: "Programmes",
    news: "Actualités",
    donate: "Donner",
    contact: "Contact",
  },
  home: {
    greeting: "Pour la bonne cause",
    lead: "Quatre programmes, une seule exigence : que chaque don serve, et que ça se voie.",
    donate: "Faire un don",
    ourPrograms: "Nos programmes",
    latestNews: "Dernières actualités",
    seeAll: "Tout voir",
    agenda: "Prochains rendez-vous",
    callUs: "Appeler l'ONG",
    noNews: "Aucune actualité publiée pour le moment.",
  },
  programs: {
    title: "Nos programmes",
    support: "Soutenir ce programme",
    openDetail: "Voir le détail",
    whatWeDo: "Ce que nous faisons",
    relatedNews: "Actualités du programme",
    noNews: "Aucune actualité publiée sur ce programme pour le moment.",
    unknown: "Ce programme n'existe pas.",
    backToList: "Revenir aux programmes",
  },
  news: {
    title: "Actualités",
    readingTime: "min de lecture",
    empty: "Aucune actualité publiée.",
  },
  donate: {
    title: "Faire un don",
    lead: "Choisissez un montant et un programme. Vous recevrez une référence à indiquer lors de votre versement Mobile Money.",
    amount: "Montant",
    other: "Autre montant",
    program: "Programme",
    general: "Don général",
    method: "Moyen de paiement",
    name: "Nom et prénoms",
    phone: "Téléphone",
    anonymous: "Rester anonyme",
    submit: "Valider mon don",
    submitting: "Enregistrement…",
    successTitle: "Merci",
    successLead: "Votre intention de don est enregistrée.",
    notPaid: "Votre don n'est pas encore encaissé.",
    keepRef: "Conservez cette référence : elle permet au Trésorier de retrouver votre versement.",
    again: "Faire un autre don",
    impact: "Concrètement",
  },
  campaigns: {
    /** Titre du bloc sur le détail d'un programme. */
    title: "Collectes en cours",
    none: "Aucune collecte en cours sur ce programme.",
    of: "de",
    donors: "participants",
    daysLeft: "jours restants",
    remaining: "Plus que",
    goalReached: "Objectif atteint — merci.",
    closed: "Collecte clôturée.",
    support: "Soutenir cette collecte",
    /** Rappel, sur le formulaire, de la collecte que l'on soutient. */
    supporting: "Vous soutenez",
    hideAmount: "Ne pas afficher le montant publiquement",
    hideAmountHint:
      "Votre nom restera dans la liste des participants, mais la somme n'y figurera pas.",
  },
  myDonations: {
    title: "Mes dons",
    lead: "Le suivi des dons faits depuis ce téléphone.",
    deviceOnly:
      "Cette liste est conservée sur CE téléphone, sans compte. Changer d'appareil la fait disparaître — c'est la référence de chaque don qui reste la preuve.",
    empty: "Aucun don enregistré pour l'instant.",
    receipt: "Télécharger le reçu",
    receiptWhenValidated: "Le reçu sera disponible dès que le Trésorier aura constaté votre versement.",
    forget: "Retirer de la liste",
    addTitle: "Retrouver un don",
    addLead: "Un don fait depuis le site ou un autre téléphone ? Saisissez sa référence et le numéro utilisé.",
    add: "Retrouver",
    adding: "Recherche…",
    addInvalid: "Indiquez une référence et un numéro complet.",
    addNotFound: "Aucun don ne correspond à cette référence et à ce numéro.",
    statuses: {
      en_attente: "En attente de validation",
      valide: "Validé par le Trésorier",
      rejete: "Rejeté",
      inconnu: "Statut indisponible",
    },
    receiptTitle: "Reçu de don",
    receiptRef: "Référence",
    receiptDeclared: "Don déclaré le",
    receiptValidated: "Versement constaté le",
    receiptFooter:
      "Ce reçu atteste d'un versement constaté par le Trésorier de l'ONG. Il ne vaut pas reçu fiscal.",
  },
  contact: {
    title: "Nous contacter",
    lead: "Chaque responsable a son domaine : appelez celui qui traite votre question.",
    call: "Appeler",
    whatsapp: "WhatsApp",
    whereTitle: "Où nous trouver",
    addressPending: "L'adresse exacte du siège est en cours de confirmation. Appelez-nous pour être guidé.",
    openMap: "Ouvrir dans les cartes",
    writeTitle: "Nous écrire",
    sendEmail: "Envoyer un email",
    notConfigured: "Les coordonnées du bureau ne sont pas encore renseignées dans cette version de l'application.",
  },
  volunteer: {
    cta: "Devenir bénévole",
    title: "Devenir bénévole",
    lead: "Dites-nous qui vous êtes et sur quel terrain vous souhaitez servir. Le Secrétariat vous rappelle.",
    fullName: "Nom et prénoms",
    phone: "Téléphone",
    email: "Adresse email",
    city: "Ville / commune",
    birthYear: "Année de naissance",
    programs: "Programmes qui vous intéressent",
    availability: "Vos disponibilités",
    skills: "Compétences particulières",
    motivation: "Pourquoi souhaitez-vous nous rejoindre ?",
    motivationHint: "20 caractères minimum",
    membership: "Je souhaite aussi adhérer comme membre cotisant.",
    optional: "facultatif",
    submit: "Envoyer ma candidature",
    submitting: "Envoi…",
    successTitle: "Candidature reçue",
    successLead: "Merci de votre engagement.",
    nextStep: "Conservez cette référence. Le Secrétariat Exécutif vous contactera au numéro indiqué.",
    backHome: "Revenir à l'accueil",
    privacy: "Vos coordonnées ne servent qu'à vous recontacter. Elles ne sont ni revendues, ni partagées.",
  },
  settings: {
    title: "Réglages",
    language: "Langue",
    rtlNotice:
      "Le passage à l'arabe inverse le sens de lecture de toute l'application : elle redémarre pour l'appliquer.",
    theme: "Apparence",
    light: "Clair",
    dark: "Sombre",
    offline: "Hors connexion — dernières données enregistrées.",
    notifications: "Notifications",
    notificationsHint:
      "Être prévenu des nouvelles campagnes, des événements et de la validation de vos dons.",
    pushRefused:
      "Notifications refusées. Android ne repose plus la question : réactivez-les dans les réglages du téléphone.",
    pushDeviceOnly: "Les notifications ne fonctionnent que sur un téléphone réel.",
    pushUnavailable: "Notifications indisponibles dans cette version de l'application.",
  },
  common: {
    loading: "Chargement…",
    error: "Une erreur est survenue.",
    retry: "Réessayer",
    close: "Fermer",
    required: "Champ obligatoire.",
  },
};

export type MobileUi = typeof mobileFr;

export const mobileAr: MobileUi = {
  tabs: {
    contact: "اتصل بنا",
    home: "الرئيسية",
    programs: "البرامج",
    news: "الأخبار",
    donate: "التبرع",
  },
  home: {
    greeting: "من أجل القضية النبيلة",
    lead: "أربعة برامج، ومطلب واحد: أن يخدم كل تبرع، وأن يظهر أثره.",
    donate: "تبرّع الآن",
    ourPrograms: "برامجنا",
    latestNews: "آخر الأخبار",
    seeAll: "عرض الكل",
    agenda: "المواعيد القادمة",
    callUs: "الاتصال بالمنظمة",
    noNews: "لا توجد أخبار منشورة حاليًا.",
  },
  programs: {
    title: "برامجنا",
    support: "ادعم هذا البرنامج",
    openDetail: "عرض التفاصيل",
    whatWeDo: "ما نقوم به",
    relatedNews: "أخبار البرنامج",
    noNews: "لا توجد أخبار منشورة عن هذا البرنامج حالياً.",
    unknown: "هذا البرنامج غير موجود.",
    backToList: "العودة إلى البرامج",
  },
  news: {
    title: "الأخبار",
    readingTime: "دقيقة قراءة",
    empty: "لا توجد أخبار منشورة.",
  },
  donate: {
    title: "التبرع",
    lead: "اختر مبلغًا وبرنامجًا. ستتلقى مرجعًا تذكره عند الدفع عبر Mobile Money.",
    amount: "المبلغ",
    other: "مبلغ آخر",
    program: "البرنامج",
    general: "تبرع عام",
    method: "وسيلة الدفع",
    name: "الاسم واللقب",
    phone: "الهاتف",
    anonymous: "أرغب في عدم ذكر اسمي",
    submit: "تأكيد التبرع",
    submitting: "جارٍ التسجيل…",
    successTitle: "شكرًا",
    successLead: "تم تسجيل نية تبرعك.",
    notPaid: "لم يتم تحصيل تبرعك بعد.",
    keepRef: "احتفظ بهذا المرجع: به يعثر أمين المال على دفعتك.",
    again: "تبرّع مرة أخرى",
    impact: "بشكل ملموس",
  },
  campaigns: {
    title: "حملات جارية",
    none: "لا توجد حملة جارية في هذا البرنامج.",
    of: "من",
    donors: "مشاركًا",
    daysLeft: "يومًا متبقيًا",
    remaining: "بقي",
    goalReached: "تم بلوغ الهدف — شكرًا لكم.",
    closed: "أُغلقت الحملة.",
    support: "دعم هذه الحملة",
    supporting: "أنت تدعم",
    hideAmount: "عدم إظهار المبلغ للعموم",
    hideAmountHint: "يبقى اسمك في قائمة المشاركين، دون أن يظهر المبلغ.",
  },
  myDonations: {
    title: "تبرعاتي",
    lead: "متابعة التبرعات التي تمت من هذا الهاتف.",
    deviceOnly:
      "تُحفظ هذه القائمة على هذا الهاتف فقط، دون حساب. تغيير الجهاز يُفقدها — والمرجع هو الدليل الباقي لكل تبرع.",
    empty: "لا توجد تبرعات مسجلة حالياً.",
    receipt: "تنزيل الإيصال",
    receiptWhenValidated: "سيتوفر الإيصال بمجرد أن يعاين أمين المال دفعتك.",
    forget: "إزالة من القائمة",
    addTitle: "استرجاع تبرع",
    addLead: "تبرعت من الموقع أو من هاتف آخر؟ أدخل المرجع والرقم المستعمل.",
    add: "استرجاع",
    adding: "جارٍ البحث…",
    addInvalid: "أدخل مرجعاً ورقماً كاملاً.",
    addNotFound: "لا يوجد تبرع مطابق لهذا المرجع وهذا الرقم.",
    statuses: {
      en_attente: "في انتظار المصادقة",
      valide: "مصادَق عليه من أمين المال",
      rejete: "مرفوض",
      inconnu: "الحالة غير متاحة",
    },
    receiptTitle: "إيصال تبرع",
    receiptRef: "المرجع",
    receiptDeclared: "تاريخ التصريح بالتبرع",
    receiptValidated: "تاريخ معاينة الدفع",
    receiptFooter:
      "يشهد هذا الإيصال بدفعة عاينها أمين مال المنظمة. وهو لا يقوم مقام إيصال ضريبي.",
  },
  contact: {
    title: "اتصل بنا",
    lead: "لكل مسؤول مجاله: اتصل بمن يعنيه سؤالك.",
    call: "اتصال",
    whatsapp: "واتساب",
    whereTitle: "أين تجدنا",
    addressPending: "العنوان الدقيق للمقر قيد التأكيد. اتصل بنا لإرشادك.",
    openMap: "فتح في الخرائط",
    writeTitle: "راسلنا",
    sendEmail: "إرسال بريد إلكتروني",
    notConfigured: "لم تُسجَّل بيانات المكتب بعد في هذه النسخة من التطبيق.",
  },
  volunteer: {
    cta: "كن متطوعاً",
    title: "كن متطوعاً",
    lead: "أخبرنا من أنت وفي أي مجال ترغب في الخدمة. ستتصل بك الأمانة التنفيذية.",
    fullName: "الاسم واللقب",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    city: "المدينة / البلدية",
    birthYear: "سنة الميلاد",
    programs: "البرامج التي تهمك",
    availability: "أوقات تفرغك",
    skills: "مهارات خاصة",
    motivation: "لماذا ترغب في الانضمام إلينا؟",
    motivationHint: "20 حرفاً على الأقل",
    membership: "أرغب أيضاً في الانضمام كعضو مشترك.",
    optional: "اختياري",
    submit: "إرسال طلبي",
    submitting: "جارٍ الإرسال…",
    successTitle: "تم استلام الطلب",
    successLead: "شكراً على التزامك.",
    nextStep: "احتفظ بهذا المرجع. ستتصل بك الأمانة التنفيذية على الرقم المذكور.",
    backHome: "العودة إلى الرئيسية",
    privacy: "لا تُستخدم بياناتك إلا للتواصل معك. لا تُباع ولا تُشارك.",
  },
  settings: {
    title: "الإعدادات",
    language: "اللغة",
    rtlNotice:
      "التحويل إلى العربية يعكس اتجاه القراءة في التطبيق كله: سيُعاد تشغيله لتطبيق ذلك.",
    theme: "المظهر",
    light: "فاتح",
    dark: "داكن",
    offline: "دون اتصال — آخر البيانات المحفوظة.",
    notifications: "الإشعارات",
    notificationsHint: "تلقّي إشعارات بالحملات الجديدة والفعاليات وتأكيد تبرعاتك.",
    pushRefused:
      "تم رفض الإشعارات. لا يعيد أندرويد طرح السؤال: فعّلها من إعدادات الهاتف.",
    pushDeviceOnly: "لا تعمل الإشعارات إلا على هاتف حقيقي.",
    pushUnavailable: "الإشعارات غير متاحة في هذه النسخة من التطبيق.",
  },
  common: {
    loading: "جارٍ التحميل…",
    error: "حدث خطأ.",
    retry: "إعادة المحاولة",
    close: "إغلاق",
    required: "حقل إلزامي.",
  },
};

const UI: Record<Locale, MobileUi> = { fr: mobileFr, ar: mobileAr };

export function getMobileUi(locale: Locale): MobileUi {
  return UI[locale] ?? mobileFr;
}
