import type { DashUi } from "./fr";

/**
 * Textes du BACK-OFFICE en arabe.
 * Typé `DashUi` : une clé ajoutée au français et oubliée ici casse le typecheck.
 */
export const dashAr: DashUi = {
  app: {
    name: "فضاء الإدارة",
    subtitle: "منظمة قرض حسن",
  },

  login: {
    title: "تسجيل الدخول",
    lead: "مخصص لمجلس الإدارة وموظفي المنظمة.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    submit: "دخول",
    submitting: "جارٍ الدخول…",
    failed: "بيانات الدخول غير صحيحة.",
    notConfigured:
      "Supabase غير مهيأ. أدخل NEXT_PUBLIC_SUPABASE_URL و NEXT_PUBLIC_SUPABASE_ANON_KEY في ملف ‎.env.local‎.",
    forbidden:
      "هذا الحساب لا يملك صلاحية الدخول إلى نظام الإدارة. المتبرعون يمرّون عبر الموقع أو التطبيق.",
    inactive: "تم تعطيل هذا الحساب. اتصل بالمصلحة الإدارية.",
  },

  nav: {
    overview: "نظرة عامة",
    donations: "التبرعات",
    finance: "المالية",
    beneficiaries: "المستفيدون",
    activities: "الأنشطة",
    communication: "الاتصال",
    administration: "الإدارة",
    documents: "الوثائق",
    logout: "تسجيل الخروج",
    menu: "تنقل نظام الإدارة",
    openMenu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
  },

  common: {
    save: "حفظ",
    saving: "جارٍ الحفظ…",
    cancel: "إلغاء",
    add: "إضافة",
    search: "بحث",
    filter: "تصفية",
    all: "الكل",
    loading: "جارٍ التحميل…",
    empty: "لا توجد بيانات حاليًا.",
    error: "حدث خطأ.",
    refresh: "تحديث",
    export: "تصدير إلى CSV",
    total: "المجموع",
    date: "التاريخ",
    amount: "المبلغ",
    program: "البرنامج",
    status: "الحالة",
    actions: "إجراءات",
    general: "عام",
    readOnly: "قراءة فقط",
    readOnlyHint: "دورك يمنحك اطلاعًا للقراءة فقط — وهذا ما يضمن استقلالية رأيك.",
    required: "هذا الحقل إلزامي.",
    of: "من",
    toLight: "التبديل إلى الوضع الفاتح",
    toDark: "التبديل إلى الوضع الداكن",
  },

  overview: {
    title: "نظرة عامة",
    lead: "حال المنظمة في شاشة واحدة: ما دخل، وما خرج، وما ينتظر قرارًا.",
    collected: "تبرعات مصادق عليها",
    collectedHint: "المجموع منذ الانطلاق",
    thisMonth: "تبرعات الشهر",
    pending: "في انتظار المصادقة",
    pendingHint: "على أمين المال مطابقتها",
    expenses: "النفقات",
    balance: "رصيد الخزينة",
    beneficiaries: "مستفيدون متابَعون",
    activitiesOngoing: "أنشطة جارية",
    byProgram: "حسب البرنامج",
    byProgramLead: "المستفيدون والتبرعات المخصصة والنفقات لكل برنامج.",
    pendingTitle: "تبرعات في انتظار المعالجة",
    pendingLead: "طابق كل دفعة مع مرجعها، ثم صادق أو ارفض.",
    seeAllDonations: "عرض كل التبرعات",
    alertsTitle: "تنبيهات",
    alertOverBudget: "تجاوز الميزانية",
    alertLateActivity: "نشاط متأخر",
    noAlerts: "لا توجد تنبيهات.",
  },

  donations: {
    title: "التبرعات والجمع",
    lead: "كل تبرع من الموقع يصل هنا في حالة انتظار. يطابق أمين المال الدفعة ثم يصادق.",
    reference: "المرجع",
    donor: "المتبرع",
    method: "الوسيلة",
    transactionRef: "رقم المعاملة",
    transactionRefHint: "الرقم الذي أرسله المشغّل إلى المتبرع برسالة قصيرة.",
    anonymous: "مجهول",
    validate: "مصادقة",
    reject: "رفض",
    rejectReason: "سبب الرفض",
    validated: "مصادَق عليه",
    rejected: "مرفوض",
    awaiting: "في الانتظار",
    validatedBy: "صادق عليه",
    receipt: "إيصال",
    recordTitle: "تسجيل تبرع مستلم بالمقر",
    recordLead:
      "نقود مسلّمة بالمقر، تحويل بنكي، تبرع من شريك: تُسجَّل هنا. يُدرج التبرع مباشرة في حالة «مصادَق عليه».",
    recordSubmit: "تسجيل التبرع",
    filterStatus: "الحالة",
    emptyPending: "لا توجد تبرعات في الانتظار. كل شيء محدَّث.",
    newDonationToast: "وصل تبرع جديد للتو.",
  },

  finance: {
    title: "المالية والمحاسبة",
    lead: "الإيرادات المصادق عليها، والنفقات المنفَّذة، والرصيد. يطّلع عليها مراقب الحسابات للقراءة.",
    income: "الإيرادات",
    expenses: "النفقات",
    balance: "الرصيد",
    addExpense: "تسجيل نفقة",
    label: "البيان",
    labelPlaceholder: "كراء حاوية — يوم النظافة",
    spentOn: "تاريخ النفقة",
    linkedActivity: "نشاط مرتبط (اختياري)",
    operating: "تسيير (خارج البرامج)",
    proofPath: "مرجع الوثيقة المثبتة (اختياري)",
    proofHint: "رقم الإيصال أو الفاتورة. رفع الملفات سيأتي مع وحدة الوثائق.",
    monthlyTitle: "التطور على 6 أشهر",
    monthlyLead: "الإيرادات المصادق عليها والنفقات، شهرًا بشهر.",
    ledgerTitle: "اليومية",
    ledgerLead: "جميع القيود، تبرعات مصادق عليها ونفقات.",
    entryIncome: "إيراد",
    entryExpense: "نفقة",
  },

  beneficiaries: {
    title: "الأعضاء والمستفيدون",
    lead: "الأشخاص الذين ترافقهم المنظمة، حسب البرنامج. بيانات حساسة: لا يُنشر منها شيء.",
    fullName: "الاسم واللقب",
    category: "الفئة",
    birthYear: "سنة الميلاد",
    phone: "الهاتف",
    address: "العنوان",
    notes: "ملاحظات المتابعة",
    add: "إضافة مستفيد",
    statusActive: "متابعة جارية",
    statusDone: "متابعة منتهية",
    statusSuspended: "موقوفة",
    assistanceTitle: "سجل المساعدات",
    assistanceAdd: "إضافة مساعدة",
    assistanceKind: "نوع المساعدة",
    assistanceKindPlaceholder: "حصة علاج طبيعي",
    assistanceDescription: "التفاصيل",
    noAssistance: "لا توجد مساعدات مسجلة لهذا الشخص.",
    categories: {
      jeune_desoeuvre: "شاب في مسار إدماج",
      enfant_popb: "طفل مصاب بشلل الضفيرة",
      famille_endeuillee: "أسرة مفجوعة",
      malade: "مريض (حالة اجتماعية)",
      apprenant: "متعلّم",
      participant_sportif: "مشارك رياضي",
      autre: "أخرى",
    },
  },

  activities: {
    title: "البرامج والأنشطة",
    lead: "ما ينظمه كل برنامج: الميزانية المخصصة، والمصروفة، ومستوى التقدم.",
    add: "برمجة نشاط",
    titleField: "العنوان",
    titleArField: "العنوان بالعربية (اختياري)",
    description: "الوصف",
    startsAt: "البداية",
    endsAt: "النهاية (اختياري)",
    place: "المكان",
    budget: "الميزانية المخصصة",
    spent: "المصروف",
    remaining: "المتبقي",
    overBudget: "تجاوز",
    isPublic: "النشر في أجندة الموقع",
    isPublicHint: "سيظهر النشاط في صفحة الفعاليات بالموقع العمومي.",
    registration: "يُستحسن التسجيل",
    report: "التقرير",
    statusPlanned: "مبرمَج",
    statusOngoing: "جارٍ",
    statusDone: "منتهٍ",
    statusCancelled: "ملغى",
  },

  communication: {
    title: "الاتصال",
    lead: "الأخبار المنشورة هنا تظهر فورًا على الموقع العمومي.",
    add: "تحرير خبر",
    slug: "معرّف الرابط",
    slugHint: "يُولَّد من العنوان؛ لا تغيّره بعد نشر المقال.",
    titleFr: "العنوان (بالفرنسية)",
    titleAr: "العنوان (بالعربية)",
    excerptFr: "الملخص (بالفرنسية)",
    excerptAr: "الملخص (بالعربية)",
    bodyFr: "المقال (بالفرنسية)",
    bodyAr: "المقال (بالعربية)",
    bodyHint: "فقرة في كل سطر. السطر الذي يبدأ بـ «##» يصبح عنوانًا فرعيًا.",
    author: "التوقيع",
    publish: "نشر",
    unpublish: "إلغاء النشر",
    draft: "مسودة",
    published: "منشور",
    archived: "مؤرشف",
    missingArabic: "النسخة العربية ناقصة",
    missingArabicHint:
      "سيُعرض المقال بالفرنسية على القراء العرب ما لم تُدخَل الترجمة.",
  },

  documents: {
    title: "الوثائق الإدارية",
    lead: "النظام الأساسي، ومحاضر مجلس الإدارة، والتقارير. الإيداع خاص افتراضيًا؛ والنشر يُظهر الوثيقة في صفحة الشفافية بالموقع.",
    add: "إيداع وثيقة",
    file: "الملف",
    fileHint: "ملف PDF أو صورة، 20 ميغابايت كحد أقصى.",
    titleFr: "العنوان",
    titleAr: "العنوان بالعربية (اختياري)",
    kind: "النوع",
    year: "السنة المالية",
    description: "الوصف (اختياري)",
    isPublic: "النشر في صفحة الشفافية",
    isPublicHint:
      "يبقى الملف مخزّنًا بشكل خاص؛ ويطلب الموقع رابطًا موقّعًا محدود المدة. لا تنشر إلا ما صادق عليه مجلس الإدارة.",
    internal: "داخلي",
    published: "منشور",
    download: "تحميل",
    downloading: "جارٍ تحضير الرابط…",
    delete: "حذف",
    confirmDelete: "حذف هذه الوثيقة نهائيًا؟",
    uploading: "جارٍ رفع الملف…",
    empty: "لا توجد وثائق مودعة.",
    linkExpires: "ينتهي رابط التحميل بعد ساعة واحدة.",
    kinds: {
      statuts: "النظام الأساسي / الوصل",
      pv_ca: "محضر مجلس الإدارة",
      rapport_activite: "تقرير النشاط",
      rapport_financier: "التقرير المالي",
      justificatif: "وثيقة محاسبية مثبتة",
      autre: "أخرى",
    },
  },

  administration: {
    title: "الإدارة",
    lead: "حسابات نظام الإدارة وسجل الإجراءات.",
    accounts: "الحسابات",
    role: "الدور",
    assignedProgram: "البرنامج المسنَد",
    active: "نشط",
    inactive: "معطَّل",
    deactivate: "تعطيل",
    reactivate: "إعادة التفعيل",
    selfEditBlocked: "لا يمكنك تعديل دورك بنفسك.",
    createHint:
      "إنشاء الحسابات يتطلب Edge Function بصلاحية service_role (لا يمكن أن يوجد ملف تعريف دون حساب مصادقة). سيُربط في الدفعة القادمة.",
    createTitle: "إنشاء حساب",
    createLead:
      "يُنشأ الحساب من جهة الخادم (مفتاح service_role): لا يمكن أن يوجد ملف تعريف دون حساب مصادقة.",
    createEmail: "البريد الإلكتروني",
    createPassword: "كلمة مرور مؤقتة",
    createPasswordHint: "8 أحرف على الأقل. تُسلَّم لصاحب الحساب الذي يغيّرها.",
    createSubmit: "إنشاء الحساب",
    created: "تم إنشاء الحساب.",
    programRequired: "يجب ربط مسؤول البرنامج ببرنامج، وإلا فلن يرى شيئًا.",
    errors: {
      forbidden: "دورك لا يسمح بإنشاء حساب.",
      email_already_exists: "يوجد حساب بهذا العنوان بالفعل.",
      password_too_short: "كلمة المرور قصيرة جدًا (8 أحرف على الأقل).",
      invalid_email: "عنوان بريد إلكتروني غير صالح.",
      invalid_name: "الاسم قصير جدًا.",
      invalid_role: "دور غير صالح.",
      program_required_for_resp: "اختر برنامج المسؤول.",
      generic: "فشل الإنشاء.",
    },
    logTitle: "سجل النشاط",
    logLead: "من فعل ماذا، ومتى. متاح لرئيس المجلس ولمراقب الحسابات.",
    logEmpty: "لا توجد إجراءات مسجلة.",
  },
};
