/**
 * Textes du BACK-OFFICE en français — source de vérité.
 * `DashUi = typeof dashFr` : toute clé ajoutée ici doit être traduite dans `ar.ts`,
 * sinon le typecheck échoue.
 *
 * Les libellés métier partagés avec le site et le mobile (rôles, programmes, moyens de
 * paiement, erreurs de validation) viennent de `@qardan/shared` — ne pas les redéfinir ici.
 */

export const dashFr = {
  app: {
    name: "Espace d'administration",
    subtitle: "ONG Qardan Hassana",
  },

  login: {
    title: "Connexion",
    lead: "Réservé au Conseil d'Administration et au personnel de l'ONG.",
    email: "Adresse email",
    password: "Mot de passe",
    submit: "Se connecter",
    submitting: "Connexion…",
    failed: "Identifiants incorrects.",
    notConfigured:
      "Supabase n'est pas configuré. Renseignez NEXT_PUBLIC_SUPABASE_URL et NEXT_PUBLIC_SUPABASE_ANON_KEY dans .env.local.",
    forbidden:
      "Ce compte n'a pas accès au back-office. Les donateurs passent par le site ou l'application mobile.",
    inactive: "Ce compte a été désactivé. Contactez le Service Administratif.",
  },

  nav: {
    overview: "Vue d'ensemble",
    donations: "Dons",
    finance: "Finances",
    beneficiaries: "Bénéficiaires",
    activities: "Activités",
    communication: "Communication",
    administration: "Administration",
    documents: "Documents",
    logout: "Déconnexion",
    menu: "Navigation du back-office",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    // Intitulés des groupes du menu — regroupement par domaine de l'ONG.
    groupPilotage: "Pilotage",
    groupFinances: "Ressources financières",
    groupTerrain: "Action sociale",
    groupInstitution: "Vie institutionnelle",
    /** Annonce, aux lecteurs d'écran, ce que fait le bouton d'un groupe. */
    expandGroup: "Déplier",
    collapseGroup: "Replier",
    /** Signale un groupe replié qui contient la page ouverte. */
    containsCurrentPage: "contient la page courante",
  },

  common: {
    save: "Enregistrer",
    saving: "Enregistrement…",
    cancel: "Annuler",
    add: "Ajouter",
    search: "Rechercher",
    filter: "Filtrer",
    all: "Tous",
    loading: "Chargement…",
    empty: "Aucune donnée pour le moment.",
    error: "Une erreur est survenue.",
    refresh: "Actualiser",
    export: "Exporter en CSV",
    total: "Total",
    date: "Date",
    amount: "Montant",
    program: "Programme",
    status: "Statut",
    actions: "Actions",
    general: "Général",
    readOnly: "Lecture seule",
    readOnlyHint:
      "Votre rôle donne un accès en lecture seule — c'est ce qui garantit l'indépendance de votre avis.",
    required: "Ce champ est obligatoire.",
    of: "sur",
    toLight: "Passer en mode clair",
    toDark: "Passer en mode sombre",
  },

  overview: {
    title: "Vue d'ensemble",
    lead: "L'état de l'ONG en un écran : ce qui est entré, ce qui est sorti, ce qui attend une décision.",
    collected: "Dons validés",
    collectedHint: "Cumul depuis l'ouverture",
    thisMonth: "Dons du mois",
    pending: "En attente de validation",
    pendingHint: "à rapprocher par le Trésorier",
    expenses: "Dépenses",
    balance: "Solde de trésorerie",
    beneficiaries: "Bénéficiaires suivis",
    activitiesOngoing: "Activités en cours",
    byProgram: "Par programme",
    byProgramLead: "Bénéficiaires, dons affectés et dépenses de chaque programme.",
    pendingTitle: "Dons à traiter",
    pendingLead: "Rapprochez chaque versement de sa référence, puis validez ou rejetez.",
    seeAllDonations: "Voir tous les dons",
    alertsTitle: "Alertes",
    alertOverBudget: "Budget dépassé",
    alertLateActivity: "Activité en retard",
    noAlerts: "Aucune alerte.",
  },

  donations: {
    title: "Dons & collecte",
    lead: "Chaque don du site arrive ici en attente. Le Trésorier rapproche le versement, puis valide.",
    reference: "Référence",
    donor: "Donateur",
    method: "Moyen",
    transactionRef: "N° de transaction",
    transactionRefHint: "Le numéro que l'opérateur a envoyé au donateur par SMS.",
    anonymous: "Anonyme",
    validate: "Valider",
    reject: "Rejeter",
    rejectReason: "Motif du rejet",
    validated: "Validé",
    rejected: "Rejeté",
    awaiting: "En attente",
    validatedBy: "Validé par",
    receipt: "Reçu",
    recordTitle: "Enregistrer un don reçu au guichet",
    recordLead:
      "Espèces remises au siège, versement bancaire, don d'un partenaire : à saisir ici. Le don est enregistré directement en « validé ».",
    recordSubmit: "Enregistrer le don",
    filterStatus: "Statut",
    emptyPending: "Aucun don en attente. Tout est à jour.",
    newDonationToast: "Un nouveau don vient d'arriver.",
  },

  finance: {
    title: "Finances & comptabilité",
    lead: "Recettes validées, dépenses engagées, solde. Le Commissaire aux Comptes y accède en lecture.",
    income: "Recettes",
    expenses: "Dépenses",
    balance: "Solde",
    addExpense: "Enregistrer une dépense",
    label: "Libellé",
    labelPlaceholder: "Location de benne — journée de salubrité",
    spentOn: "Date de la dépense",
    linkedActivity: "Activité liée (facultatif)",
    operating: "Fonctionnement (hors programme)",
    proofPath: "Référence du justificatif (facultatif)",
    proofHint: "N° de reçu ou de facture. Le dépôt de fichier viendra avec le module Documents.",
    monthlyTitle: "Évolution sur 6 mois",
    monthlyLead: "Recettes validées et dépenses, mois par mois.",
    ledgerTitle: "Journal",
    ledgerLead: "Toutes les écritures, dons validés et dépenses confondus.",
    entryIncome: "Recette",
    entryExpense: "Dépense",
  },

  beneficiaries: {
    title: "Membres & bénéficiaires",
    lead: "Les personnes accompagnées par l'ONG, par programme. Données sensibles : rien de tout ceci n'est publié.",
    fullName: "Nom et prénoms",
    category: "Catégorie",
    birthYear: "Année de naissance",
    phone: "Téléphone",
    address: "Adresse",
    notes: "Notes de suivi",
    add: "Ajouter un bénéficiaire",
    statusActive: "Suivi actif",
    statusDone: "Suivi terminé",
    statusSuspended: "Suspendu",
    assistanceTitle: "Historique d'assistance",
    assistanceAdd: "Ajouter une aide",
    assistanceKind: "Nature de l'aide",
    assistanceKindPlaceholder: "Séance de kinésithérapie",
    assistanceDescription: "Détail",
    noAssistance: "Aucune aide enregistrée pour cette personne.",
    categories: {
      jeune_desoeuvre: "Jeune en réinsertion",
      enfant_popb: "Enfant POPB",
      famille_endeuillee: "Famille endeuillée",
      malade: "Malade (cas social)",
      apprenant: "Apprenant",
      participant_sportif: "Participant sportif",
      autre: "Autre",
    },
  },

  activities: {
    title: "Programmes & activités",
    lead: "Ce que chaque programme organise : budget alloué, budget dépensé, avancement.",
    add: "Planifier une activité",
    titleField: "Intitulé",
    titleArField: "Intitulé en arabe (facultatif)",
    description: "Description",
    startsAt: "Début",
    endsAt: "Fin (facultatif)",
    place: "Lieu",
    budget: "Budget alloué",
    spent: "Dépensé",
    remaining: "Reste",
    overBudget: "Dépassement",
    isPublic: "Publier à l'agenda du site",
    isPublicHint: "L'activité apparaîtra sur la page Événements du site public.",
    registration: "Inscription souhaitée",
    report: "Compte rendu",
    statusPlanned: "Planifiée",
    statusOngoing: "En cours",
    statusDone: "Terminée",
    statusCancelled: "Annulée",
  },

  communication: {
    notify: "Notifier",
    notifyHint: "Envoyer une notification aux porteurs de l'application mobile.",
    notifySending: "Envoi en cours…",
    notifySent: "Notification envoyée",
    notifyFailed: "Envoi impossible. Vérifiez votre rôle et réessayez.",
    title: "Communication",
    lead: "Les actualités publiées ici apparaissent immédiatement sur le site public.",
    add: "Rédiger une actualité",
    slug: "Identifiant d'URL",
    slugHint: "Généré depuis le titre ; ne plus le changer une fois l'article publié.",
    titleFr: "Titre (français)",
    titleAr: "Titre (arabe)",
    excerptFr: "Résumé (français)",
    excerptAr: "Résumé (arabe)",
    bodyFr: "Article (français)",
    bodyAr: "Article (arabe)",
    bodyHint: "Un paragraphe par ligne. Une ligne commençant par « ## » devient un sous-titre.",
    author: "Signature",
    publish: "Publier",
    unpublish: "Dépublier",
    draft: "Brouillon",
    published: "Publié",
    archived: "Archivé",
    missingArabic: "Version arabe manquante",
    missingArabicHint:
      "L'article s'affichera en français aux lecteurs arabophones tant que la traduction n'est pas saisie.",
  },

  documents: {
    title: "Documents administratifs",
    lead: "Statuts, PV du Conseil d'Administration, rapports. Le dépôt est privé par défaut ; publier expose le document sur la page Transparence du site.",
    add: "Déposer un document",
    file: "Fichier",
    fileHint: "PDF ou image, 20 Mo maximum.",
    titleFr: "Intitulé",
    titleAr: "Intitulé en arabe (facultatif)",
    kind: "Nature",
    year: "Exercice",
    description: "Description (facultatif)",
    isPublic: "Publier sur la page Transparence",
    isPublicHint:
      "Le fichier reste stocké en privé ; le site en demandera une URL signée à durée limitée. Ne publier que ce qui a été validé par le Conseil d'Administration.",
    internal: "Interne",
    published: "Publié",
    download: "Télécharger",
    downloading: "Préparation du lien…",
    delete: "Supprimer",
    confirmDelete: "Supprimer définitivement ce document ?",
    uploading: "Envoi du fichier…",
    empty: "Aucun document déposé.",
    linkExpires: "Le lien de téléchargement expire au bout d'une heure.",
    kinds: {
      statuts: "Statuts / récépissé",
      pv_ca: "PV de Conseil d'Administration",
      rapport_activite: "Rapport d'activité",
      rapport_financier: "Rapport financier",
      justificatif: "Justificatif comptable",
      autre: "Autre",
    },
  },

  administration: {
    title: "Administration",
    lead: "Comptes du back-office et journal des actions.",
    accounts: "Comptes",
    role: "Rôle",
    assignedProgram: "Programme affecté",
    active: "Actif",
    inactive: "Désactivé",
    deactivate: "Désactiver",
    reactivate: "Réactiver",
    selfEditBlocked: "Vous ne pouvez pas modifier votre propre rôle.",
    createHint:
      "La création de comptes exige une Edge Function en service_role (un profil ne peut pas exister sans compte d'authentification). À brancher au prochain lot.",
    createTitle: "Créer un compte",
    createLead:
      "Le compte est créé côté serveur (clé service_role) : un profil ne peut pas exister sans compte d'authentification.",
    createEmail: "Adresse email",
    createPassword: "Mot de passe provisoire",
    createPasswordHint: "8 caractères minimum. À communiquer au titulaire, qui le changera.",
    createSubmit: "Créer le compte",
    created: "Compte créé.",
    programRequired: "Un responsable de programme doit être rattaché à un programme, sinon il ne verra rien.",
    errors: {
      forbidden: "Votre rôle ne permet pas de créer un compte.",
      email_already_exists: "Un compte existe déjà avec cette adresse.",
      password_too_short: "Mot de passe trop court (8 caractères minimum).",
      invalid_email: "Adresse email invalide.",
      invalid_name: "Nom trop court.",
      invalid_role: "Rôle invalide.",
      program_required_for_resp: "Choisissez le programme du responsable.",
      generic: "La création a échoué.",
    },
    logTitle: "Journal d'activité",
    logLead: "Qui a fait quoi, et quand. Consultable par le PCA et le Commissaire aux Comptes.",
    logEmpty: "Aucune action enregistrée.",
  },
};

export type DashUi = typeof dashFr;
